### ISSUE TITLE
saga can't get action's result on server

### ISSUE THREAD

**Issue by Mantak** [bmealhouse/next-redux-saga#1]
these code can both print on client, but only one on server

file 1 // someSaga.js
if ( true ) {
  dispatch({type: 'HELLO'})
}
file 2 // someReducer.js
    case 'HELLO': {
      console.log('i can print'');
    }
file 3// someSaga.js
    takeLatest('HELLO', ()=> console.log('i can't print'))

**Comment by Mantak** [comment]
the question is :
saga1 -> put({type: 'abc'})  ->  saga2
when render on server:
if saga1 put an action to start saga2,  the application don't wait this

**Comment by bmealhouse** [comment]
@Mantak Thanks for submitting this issue.  I will take a look when I have a chance.  PRs are welcome.

**Comment by bmealhouse** [comment]
@Mantak - I'm still not sure how to handle this, but I believe it needs be handled in the logic of your sagas.  I added a comment to [this](https://github.com/redux-saga/redux-saga/issues/255#issuecomment-321860304) thread to see if others have solved this problem.

**Comment by Mantak** [comment]
@bmealhouse  Thank you for your effort

**Comment by bmealhouse** [comment]
Closing this issue.  Please refer to my previous comment for solution.
