### ISSUE TITLE
state lost on the client side

### ISSUE THREAD

**Issue by arfa** [bmealhouse/next-redux-saga#15]
I had an issue when I setup up `next-redux-saga`

My page renders properly on Server side and correct html is sent to client.
The issue here is on client side, my page renders again and the state on client side seems to be different from that of server.

I fixed that when I specified `preloadedState`.
(I was not using an `preloadedState` for my app as it is optional. the reducers initiate my store)

It is mentioned [here](https://redux.js.org/recipes/structuringreducers/initializingstate) and [here](https://github.com/reduxjs/redux/issues/1189) but I think it should be mentioned in your doc too.

**Comment by arfa** [comment]
in the sample you are giving in [this repository ](https://github.com/bmealhouse/next-redux-saga)

In `next-redux-saga/test/store/configure-store.js`, 
try to remove `initialState` from the `createStore` function.

You will get an error !

in this [comment](https://github.com/reduxjs/redux/issues/1189#issuecomment-168025590) Dan Abramov said: **You can pass the whole initial state tree as a second argument when creating the store. This is useful for hydrating persisted data or data received from the server.**

People who are coming from the SPA world know that `initialState` is optional and they can use the `reducers` to initiate the store. So they can be confused when they get that error, specially that the error is not explicit 

I suggest to specify this in the doc !

**Comment by bmealhouse** [comment]
@arfa - I will update the docs. Thanks for pointing that out.
