### ISSUE TITLE
Complete example of calling API on backend with multiple sagas?

### ISSUE THREAD

**Issue by ivanakimov** [bmealhouse/next-redux-saga#18]
I've found this: https://github.com/redux-saga/redux-saga/issues/255#issuecomment-323747994

But it's not enough to understand how the execution of the page is paused until API call finishes (and at which point do you call `dispatch(END)` -- at the end of `getInitialProps`?). When I try to make it work with an actual API call, I get this:

```
TypeError: Cannot read property 'done' of undefined
    at Function._callee$ (.../node_modules/next-redux-saga/dist/next-redux-saga.umd.js:198:45)
```

Are there any examples of using `next-redux-saga` with an actual API call in a complete mini-example?

**Comment by bmealhouse** [comment]
Sorry @ivanakimov, unfortunately I won't have time to check out this issue for another 2-3 weeks. The `next-redux-saga` repo itself has an example app with async sagas. Just clone the repo and run `yarn start`. Is this sufficient?

If not, you can also check out the example in the [Next.js repo](https://github.com/zeit/next.js/tree/canary/examples/with-redux-saga).

**Comment by ivanakimov** [comment]
Thank you for the quick response @bmealhouse.

I think the issue is the counter example is not too "real-world". If it could pull from some API, and then call another saga (all on the backend, and only then issue `@@redux-saga/CHANNEL_END` to respond to the client) - that would be very useful.

Anyway, I know everyone's time is limited. I'm going to close this issue since it was more of a question, but that would definitely be a nice example to explore. Maybe something to think about adding if you get a free moment. Thanks for the module!

**Comment by abelta** [comment]
Can we reopen this one?
I agree that it's difficult to translate the given example into an API call.
Either that or I'm doing something wrong but I can't make it work for me.

**Comment by bmealhouse** [comment]
@abelta - We can open this back up, but I won't have much time to work on this in the coming weeks.

If either of you (@ivanakimov, @abelta) are interested in getting a PR started, I'd be happy to work with you to get this merged.

**Comment by abelta** [comment]
@bmealhouse I would gladly provide a PR but I'm not even sure if it's a bug in the library or something I'm doing wrong.
What I've noticed so far is that I can delay execution of rendering with getInitialProps for one action but not for two. In the case of a call to API you would normally use at lest two actions: one where the call is requested and a second one when it's been resolved as successful (or unsuccessful). If I initiate a request action, execution resumes immediately instead of waiting for the call to be made.

Is this a problem with the library, with the _app module, with how I getInitialProps is scripted? This is as far as I go.

**Comment by bmealhouse** [comment]
@abelta - Just open up a PR with what you have so far. I will take a look at it and help you get everything working. You may need to give me commit access to your forked repository. Let me know if you have any questions.

**Comment by abelta** [comment]
@bmealhouse Not as a PR but I've repoed the example project I'm working on and you can find it here: https://github.com/abelta/pokedex-next
In *pages>index.js*, in the _getInitialProps_ method is where I'm trying to trigger an action that should retrieve the data from a web service.
I know for a fact that it works in browser mode but in the case of consecutive calls to sagas, it stop after the first action/saga is complete.

**Comment by bmealhouse** [comment]
@abelta - At first glance (without running this on my laptop), I noticed you are using **spawn** in all your sagas. This does not work with server-side rendering so you’ll have to use **fork** instead.

> All forked tasks are attached to their parents. When the parent terminates the execution of its own body of instructions, it will wait for all forked tasks to terminate before returning.

Spawn creates a detached task and it’s not guaranteed to complete before the server returns a response to the client.

**Comment by abelta** [comment]
You are right. Changing `spawn` for `fork` and changed `getInitialProps` to be an async function and it works beautifully now. Thank you.

**Comment by bmealhouse** [comment]
That’s great! Are you still interested in submitting a PR with your example?

**Comment by iasinov** [comment]
@bmealhouse hi! Thank you for the HOC!
In the demo app only root reducer & root saga are being used.
I'm trying to inject dynamically reducers and sagas to the components.
The idea is to initialize the component like this:
```
const withConnect = connect(mapStateToProps, {
  getPromo,
});
const withReducer = injectReducer({ key: 'test', reducer });
const withSaga = injectSaga({ key: 'test', saga });

const Index = compose(
  withReducer,
  withSaga,
  withConnect,
)(IndexComponent);

export default Index;
```
As for the reducers, it was quite easy by using something like:
```const injectReducer = (key, reducer) => (WrappedComponent) => {
  const Extended = (props, context) => {
    const { store } = context;
    store.injectReducer(key, reducer);
    return <WrappedComponent {...props} />;
  };
  Extended.contextTypes = {
    store: shape(),
  };
  return Extended;
};
```
and modifying configureStore to
```function configureStore(initialState = {}) {
  const store = createStore(
    createReducer(),
    fromJS(initialState),
    bindMiddleware([sagaMiddleware]),
  );
  store.runSagaTask = () => {
    store.sagaTask = sagaMiddleware.run(saga);
  };
  store.runSagaTask();
  store.asyncReducers = {};
  store.injectReducer = ({ key, reducer }) => {
    store.asyncReducers[key] = reducer;
    store.replaceReducer(createReducer(store.asyncReducers));
    return store;
  };
  return store;
}
```
But I cannot find a way to inject sagas similar way. When trying to implement the way it's like there:
https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/injectSaga.js
I get the same error mentioned at the beginning of the thread:
```
TypeError: Cannot read property 'done' of undefined
    at Function._callee$ (.../node_modules/next-redux-saga/dist/next-redux-saga.umd.js:198:45)
```
That would be super helpful if you could give at least the idea of how it can be implemented (if possible).
Thank you in advance

**Comment by bbortt** [comment]
I'll close this due to inactivity.
