### ISSUE TITLE
Using NextJS router.push from within saga stops working with next-redux-saga

### ISSUE THREAD

**Issue by jbox5** [bmealhouse/next-redux-saga#26]
Hi,

I've got a really simple saga that does nothing other than use NextJS 7 router and does a Router.push (using `call(Router.push, '/mypath')`).
However, the navigation does not happen.  If I remove the 'withReduxSaga' HOC wrapper from my _app.js it begins working again.

Is there anything special I have to do when using next-redux-saga to make this work?

Thanks,
J.

**Comment by bmealhouse** [comment]
Hi @jbox5, thanks for submitting the issue. Unfortunately, I don't have any time to devote to this project at the moment, but I'm happy to accept PRs or share commit rights with those interested in supporting `next-redux-saga`.

Please see the [contributing docs](https://github.com/bmealhouse/next-redux-saga#contributing) to get started.

**Comment by bbortt** [comment]
Hi @jbox5 
Are you sure you're on the client side of your application? You need to redirect using `req.redirect('some-url')` on the server side. You can detect the current context using `ctx.isServer` withing `#getInitialProps`.

**Comment by wootencl** [comment]
@bbortt I was hoping you were correct in your assumption of server vs client routing but unfortunately I'm seeing this on my end as well. Seems using `call(Router.push, '/insights/overview')` has no affect whatsoever 😞. Will see if I can do some digging, but anyone with knowledge with this package may be better suited for the task than myself. 

@jbox5 Assuming you weren't able to get this working?

**Comment by wootencl** [comment]
Realized the actual logic of this module is ~40 lines of code so domain knowledge probably doesn't really apply 😅.

Slight update though: it would seem that the usage of `call` itself is what's causing the problem. Using the router outside of call (e.g. - `Router.push('/path`) seems to work just fine. Probably move forward with this approach but maybe something worthwhile investigating if someone has interest/time.

**Comment by wootencl** [comment]
A little embarrassed here, but... I had forgotten to precede the `call` with a `yield` 🤦‍♂️. With a `yield` in front (e.g. -  `yield call(Router.push, '/path');` everything works as expected. Feel free to close this issue

**Comment by bbortt** [comment]
@wootencl  Thank you very much for posting the solution. I was thinking about this ratter being a `redux-saga` issue, but its solved then 👍
