### ISSUE TITLE
Problems with Next.js redux-saga sample code when redux-saga version is changed to ^1.0.0

### ISSUE THREAD

**Issue by robert-barcelona** [bmealhouse/next-redux-saga#27]
I don't know if this is related to next-redux-saga or not -- but when I tried to move the Next.js redux-saga sample code, which relies on next-redux-saga, to my project, it didn't work.  The only difference I could see was that the sample code uses redux-saga 0.16.0 and my project uses ^1.0.0.  When I switched my project to use redux-saga 0.16.0 it worked fine.  

I was tracing through the output and saw that the redux-saga task seems to have a `done` field with version 0.16.0 but now it has a `toPromise` field with version ^1.0.0 and wondered whether next-redux-saga were relying on `done` in some way?

**Comment by bmealhouse** [comment]
Hi @robert-barcelona, thanks for submitting the issue. Unfortunately, I don't have any time to devote to this project at the moment, but I'm happy to accept PRs or share commit rights with those interested in supporting `next-redux-saga`.

Please see the [contributing docs](https://github.com/bmealhouse/next-redux-saga#contributing) to get started.

**Comment by robert-barcelona** [comment]
Hi @bmealhouse  -- I forked the code and went through it.  I've never edited an NPM package before but I'm happy to do so.  Is 'index.js' the only file which constitutes the package?  The only reference to 'done' in this file that I can find is line 26
`        await store.sagaTask.done`
I changed this to 

`        await store.sagaTask.toPromise`
but it didn't seem to make any difference.

As said, I'm a beginner with all this - if you can provide any clues, that'd be great....

**Comment by robert-barcelona** [comment]
@martinkadlec0  -- Thanks, done and it seems to work.  I've created a pull request ...

**Comment by bbortt** [comment]
Yes, we should update the `package.json` - currently all dependencies are listed as dev.. I'm starting a branch [here](https://github.com/bbortt/next-redux-saga/tree/feature/update_dependency_listing_in_package_json).

**Comment by Andarist** [comment]
I'm maintainer of redux-saga and we got a report [here](https://github.com/redux-saga/redux-saga/issues/1743#issuecomment-458461702) about broken integration with this package.

I'd like to help, but I would have to understand how things work here first. I understand that you (@bmealhouse) have limited time and probably no interest in maintaining this package anymore, but maybe you could shed some light on this one.

I'm not too familiar with SSR practices - so I might miss something, but is there any practical reason for ENDing a saga on the client (and having to restart it later in that case)? Couldnt we just skip this step on the client and do it solely on the server?

**Comment by bmealhouse** [comment]
Thank you all for helping out on this.

@Andarist - the only reason we are ENDing the saga on the client, is to provide consistent behavior with how Next.js works out if the box. We call that “sync” mode and it’s the default for next-redux-saga. However, there is an option to use “async” mode, which does not END the saga on the client (this is my preferred way of using next-redux-saga).

Does that help?

**Comment by Andarist** [comment]
> Does that help?

To some extent - yes 😅 It's good that "async" mode works without dispatching END on the client. 

The followup question would be - how would the behaviour change if we would just do the async mode the default? How sync and async differ?

**Comment by bmealhouse** [comment]
We decided to make “sync” the default because that matches more closely to how Next.js works out of the box. I’m fine with changing the default to “async” if that is the recommended approach for redux-saga.

The difference between “sync” and “async” is mostly related to route changes. After clicking a link, “sync” waits for sagas to END, then changes to the new route. “async” will immediately perform the route change while processing the sagas in the background. See our README for more details.

Let me know if you have anymore questions.

**Comment by bbortt** [comment]
Besides changing the default to async.. @Andarist can you explain me why ` await store.sagaTask.toPromise()` seems not to do the same job as `await store.sagaTask.done`?

**Comment by Andarist** [comment]
It does the same. The problem here is that in previous version of redux-saga each saga got its own instance of internal stdChannel (its a channel which receives dispatched actions from redux and which is used to resolve `take` effects). However using 1 stdChannel per saga lead to some scheduling edge cases which we couldn't cover with it. 

Conceptually we need only a single stdChannel (multicast) to resolve all pending `take`s - each action should land on the same queue (instead of multiple ones - like in the previous implementation).

So the actual difference here is that this package has worked before because it was possible (kinda by accident) to "restart" saga as each saga got its own, brand new stdChannel. However right now it gets closed (like any channel) when you dispatch END, so saga can't be just restarted as it won't be able to take from a closed stdChannel.

**Comment by bbortt** [comment]
Ah that clarifies it for me. Thank you very much.
So in case of the synchronous client we would have to recreate instead of just restart the channel, am I right?
Are you under pressure or is it ok if I try to implement this?

**Comment by Andarist** [comment]
Actually - I'd prefer you implementing this, because I have no Next.js experience and I don't quite grasp all repercussions that refactor could have.

> So in case of the synchronous client we would have to recreate instead of just restart the channel?

Yes, exactly.

**Comment by ezhlobo** [comment]
@bbortt if there is a way that you can split these changes into a list of items, that would be awesome. This way others will be able to help you with the problem.

For now it's hard to understand what's left to make it work.

**Comment by bbortt** [comment]
Hi @ezhlobo 

Glad you'd like to help. We're currently stuck because there seems to be no way of restarting a closed redux-saga channel at the moment.
Take a look at [this conversation](https://github.com/bbortt/next-redux-saga/pull/1) for more detailed information.

**Comment by bmealhouse** [comment]
@bbortt - Does it help to just remove support for `sync` mode and force the next major version of `next-redux-saga` to only work with `async` mode?

**Comment by bbortt** [comment]
Yes, this basically is the problem @bmealhouse ..

**Comment by bmealhouse** [comment]
@bbortt - I’m ok with dropping support for sync mode, especially since redux-saga is designed to run async.

It would also simplify the API of next-redux-saga as there would be no configuration options.

Thanks for all your help on this. Much appreciated!

**Comment by bbortt** [comment]
@bmealhouse No problem at all :)
Then we just need to stop saga on the server, right? I've updated the pull-request..

**Comment by bbortt** [comment]
We finally managed to push to `redux-saga: 1.0.0`. Stay tuned for the next release.

**Comment by bmealhouse** [comment]
@bbortt  @ezhlobo - v4 has been released.

**Comment by bbortt** [comment]
Thank you @bmealhouse !

**Comment by janjarfalk** [comment]
I think there is an issue with the latest version of `next-redux-saga` and/or the example implementation of it in the next.js repo - https://github.com/zeit/next.js/tree/canary/examples/with-redux-saga. 

I created an issue in the next.js repo - https://github.com/zeit/next.js/issues/6308 - yesterday and then later found this thread. 

The issue regarding inconsistent data feels related to above discussion.

**Comment by bmealhouse** [comment]
@janjarfalk - It looks like the example needs some more updates to be compatible with next-redux-saga v4.

Feel free to open a PR with next.js with v4 API changes.

**Comment by bbortt** [comment]
@bmealhouse thought the same. 
@janjarfalk We're not doing anything different than with `"redux-saga": "0.16.2"`..
We should track this in the `zeit/next.js` issue!
