### ISSUE TITLE
Kea-saga

### ISSUE THREAD

**Issue by etiennemtl** [bmealhouse/next-redux-saga#45]
Hi guys, some help would be appreciated here, i'm trying to integrate kea-saga with your library. The probleme is the saga is never run when the page is loaded via SSR. I've made an example [here](https://github.com/etiennemtl/next.js/tree/with-kea-saga/examples/with-kea-saga). Maybe you could guide to the last bit that I miss.

**Comment by bbortt** [comment]
Hi @etiennemtl 
This library is currently not compatible with `react-redux: 1.0.1`. Try `"redux-saga": "0.16.2"` and take a look at [this pull-request](https://github.com/bmealhouse/next-redux-saga/pull/44) for more information.
Apart from this, why are you using `axios` and `isomorphic-unfetch` at the same time? I'd suggest you to choose one of them :)

**Comment by etiennemtl** [comment]
I dowgraded the version of `redux-saga` to `0.16.2`, but now the application is just in a continuous loop when requesting the page.

**Edit:** I've removed `isomorphic-unfetch`, I've started the example from the `with-kea` example and forgot to removed the dependencie. Good catch! :)

**Comment by bbortt** [comment]
Are you fine if I take a look at this again if version 4.0 is out? It contains API breaking changes..

**Comment by etiennemtl** [comment]
Yes makes sense! 

I've been investigating a bit more the issue on my side and I have been able to make the saga run server-side, but then the saga are not registered client side and thus then are not fired when an actions is dispatch. I had to modify a bit the `hoc` function to make this work in order to activate the `kea-saga` plugin. My guess is that it's probably just a matter of registering the plugin at the right time for server/client side. I've tried to look at the `kea-saga` to understand a bit more how the sagas are being registered and run, but I had some difficulties understand to lifecycle.

**Comment by bbortt** [comment]
Hi @etiennemtl , any progress on this one using the latest releases? I may have time to look a bit into it this week :)

**Comment by etiennemtl** [comment]
Hi @bbortt, I've updated the example to use the latest release. The page is stuck in an infinite loading loop. You can get the latest code here: https://github.com/etiennemtl/next.js/tree/with-kea-saga/examples/with-kea-saga

**Comment by etiennemtl** [comment]
Maybe this can help figure out a solution: https://github.com/keajs/kea/issues/60.
Although the problem seems to be on the kea side of things and with the way the register their global plugins.

**Comment by bbortt** [comment]
Sorry for the (very) late response, I honestly thought I would have written a comment about a month ago.
I did indeed take a look at your project when i wrote [this comment](https://github.com/bmealhouse/next-redux-saga/issues/45#issuecomment-465076788) and thought that the problem must be located in the `kea` code. Because all your redux-saga and next-redux-saga code looked good.
So my suggestion is to keep tracking of the kea-issue and see if anyone responds to it. By the way: you didn't really ask a question - your comment looks pretty unfinished to me ;)

**Comment by etiennemtl** [comment]
Ok so i've made some progress, I've manage to make kea-saga work although with some issues, maybe you could help with them pointing me in the right direction.

**store.js**
```js
export const configureStore = (preloadedState = {}) => {
  const store = getStore({
    paths: ['kea', 'concepts'],
    plugins: [sagaPlugin],
    preloadedState,
  }) as SagaStore

  return store
```
**Page.js**
```js
import logic from './logic'
import { connect } from 'kea'
import 'kea-saga/install'
import hoistNonReactStatics from 'hoist-non-react-statics'

const connectedLogic = connect({
  actions: [
    logic, ['fecthXYZ']
  ],
  props: [
    logic, ['xyz']
  ]
})

class Page extends Component {
  // This now gets called because of hoistNonReactStatics
  static async getInitialProps(ctx) {
    // Needed by next-redux-saga
    ctx.store.sagaTask = ctx.store._sagaMiddleware.run(connectedLogic.saga)
    // Then call the action that will trigger the saga
    ctx.store.dispatch(logic.fetchXYZ())
  }

  render() {
    // All props are now defined
    const { xyz, fetchXYZ } = this.props
    return (<div></div>)
  }
}

const ComposedComponent = compose(
  connectedLogic,
)(Page)
// Copy static properties into the Composed component (default export)
export default hoistNonReactStatics(ComposedComponent, Page)
```

First issue is how the store `sagaTask` gets registered, the only way I could make this to work is by assigning the task in the `getInitialProps` of each page, with the `connectedLogic` saga. I've tried combining all the logics and making a `rootsaga` without success. Therefore obligating me to include each logic used by child component of the page into the `connectedlogic`, else the saga won't fire.

Second issue is that I have to copy the getInitialProps from the Page into the ComposedComponent, else it never gets called.

Third issue, is that there is big double render with a blank screen between the two render. I know it may be caused by the store et connected component not being registered correctly, because I need to add the `import 'kea-saga/install'` on top of every page or the saga or not firing client side.

**Comment by bbortt** [comment]
Hi @etiennemtl 
First of all, I've to admit again that I don't know anything about `kea` nor `kea-saga`.
But, I can help you with the problem to include the `#getInitialProps({ctx})` in every component.
> Second issue is that I have to copy the getInitialProps from the Page into the ComposedComponent, else it never gets called.

There's a super-component called `_app.js` which wraps all next pages. I'd connect your pages there. And of course, you'll have to pass/call the function in every sub-component again.
What do you mean by "double-render"? Two initial page loads, two `getInitialState` dispatches..?

Is your code still available anywhere? Maybe it some parts clarify if I could try it out :)

**Comment by bbortt** [comment]
Tag: `stale`
