### ISSUE TITLE
considerations on stopping saga tasks on server side

### ISSUE THREAD

**Issue by bbortt** [bmealhouse/next-redux-saga#48]
Bug reported [here](https://github.com/bmealhouse/next-redux-saga/issues/27) and [here](https://github.com/zeit/next.js/issues/6308).

**Comment by bbortt** [comment]
Current behaviour:
```
request 1 -> ssr -> rendered page with saga data
request 2 -> ssr -> rendered page without saga data (saga task stopped)
```
```
request 1 -> ssr -> rendered page with saga data
request 2 -> ssr -> rendered page with saga data
```

Problem: If we don't await all tasks to be resolved (`dispatch(END)`) we won't have any data on ssr result.

**Comment by bbortt** [comment]
Solution I can think of: User has to manually dispatch an action as soon as he loaded all data. We then hook on this action.. I've started something like this [here](https://github.com/bbortt/next-redux-saga/tree/bugfix/considerations-on-stopping-saga-tasks-on-server-side?files=1) but tried to dispatch the action in our hook what (as expected) didn't work.

**Comment by bmealhouse** [comment]
@bbortt - Why is the saga task stopped on the second request?

The store should be recreated by `next-redux-wrapper` for every SSR request, which would also create a new `sagaTask` for every request. `next-redux-saga` must `dispatch(END)` to return data to the client.

**Comment by bmealhouse** [comment]
If I find some time this weekend, I will take a look at what's going on.

**Comment by bbortt** [comment]
@bmealhouse I dont't know why the store is not running. I may take a look at the wrapper tomorrow..

**Comment by bbortt** [comment]
@bmealhouse Maybe we just need to update the redux-wrapper to 3.0.0-alpha.. I'm on phone and cannot test it rightnow.

**Comment by bmealhouse** [comment]
@bbortt - Yeah, that's possible. We may need to go to the alpha version of `next-redux-wrapper`. I will let you know if I have time to look at it and what I find.

**Comment by janjarfalk** [comment]
I did try upgrade the `with-redux-saga` example to next-redux-wrapper@3.0.0-alpha.1. Did not work.

**Comment by bbortt** [comment]
The mistake must be located in the zeit/next.js example!
I've got a working ssr [here](https://github.com/bbortt/my-little-streaming-dream/tree/master/parent/frontend/web-ui), using `"next-redux-saga": "4.0.0"` and `"redux-saga": "1.0.1`.
That's also where I tested the v4.0 release and therefore why I was so confused about the report. But I've just double checked it this morning and it works 100%.

**Comment by jfbaraky** [comment]
Still having this problem with `"next-redux-saga": "4.0.2"` and `"redux-saga": "1.0.2"` :(
