### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by virzak** [bmealhouse/next-redux-saga#5]
Hello,

Are typescript definitions available for this project?

**Comment by bmealhouse** [comment]
No they aren't.  Are you interested in making a PR to add them?

**Comment by richbai90** [comment]
Here is a very simple typing that seems to do the job at least for the basic setup. I'm using it in my app with no problems.

```ts
declare module 'next-redux-saga' {
  function withReduxSaga<T extends React.Component>(arg: function | Partial<{[index : string] : any; async: boolean; }>) : T
  export default withReduxSaga;
}
```

**Comment by bmealhouse** [comment]
Thanks for sharing @richbai90.

**Comment by leocavalcante** [comment]
Thanks @richbai90 
I slightly modified to:
```ts
declare module "next-redux-saga" {
  function withReduxSaga<P = any>(arg: function | Partial<{ [index: string]: any; async: boolean; }>): ComponentType<P>
  export default withReduxSaga;
}
```

Because of `next-redux-wrapper` expecting a `ComponentType<P = {}>`.

**Comment by bmealhouse** [comment]
If either of you are interested, feel free to submit a PR to definitely typed.

**Comment by leocavalcante** [comment]
I think you can close this now ;)

**Comment by bmealhouse** [comment]
Much appreciated @leocavalcante!
