### ISSUE TITLE
Image and css not working

### ISSUE THREAD

**Issue by sivakumarjsl** [bmealhouse/next-redux-saga#72]
css  error  when i was import file in _app.js. like you need a proper loader for this css. and image(public folder) also not appearing in inside the page folder file.

**Comment by bbortt** [comment]
that's clearly not a `next-redux-saga` problem. you need to take a look at [webpack `css-loader`](https://webpack.js.org/loaders/css-loader/) (for css) and/or [webpack `url-loader`](https://webpack.js.org/loaders/url-loader/) (for images or similar) ;)
