### ISSUE TITLE
takeLatest doesn't execute the generator function on server

### ISSUE THREAD

**Issue by dxit** [bmealhouse/next-redux-saga#73]
This code works perfectly on client, but it gets stuck on server side:

**sagas.ts**
```typescript
import { all, call, takeLatest } from 'redux-saga/effects';
import api from '../../../api';
import { handleError } from '../../../store/sagas';
import { fetchHomepage } from './actions';
import { HomepageTypes } from './types';

function* handleRequest() {
	yield takeLatest(HomepageTypes.REQUEST, handleHomepage);
}

export function* handleHomepage() {
	console.log('**************************************** DEBUG');
	try {
		const res = yield all([call(api.get, '/encodery/homepage'), call(api.get, '/wp/v2/pages?slug=homepage')]);
	} catch (e) {
		yield call(handleError, e, fetchHomepage);
	}
}

function* watchFetchHomepage() {
	yield call(handleRequest);
}

export default watchFetchHomepage;
```

**homepage.tsx**
```typescript
import { NextPage } from 'next';
import React from 'react';
import { fetchHomepage } from '../components/homepage/store/actions';

const Home: NextPage = () => {
	return (
		<div>Homepage testing</div>
	);
};

Home.getInitialProps = async ({ store }) => {
	store.dispatch(fetchHomepage.request());
	console.log(store.getState().homepage.loading);
	return {};
};

export default Home;
```

So, apparently, `yield takeLatest(HomepageTypes.REQUEST, handleHomepage)` executes correctly the action (`HomepageTypes.REQUEST`), but it doesn't execute `handleHomepage`.
I suppose so because `HomepageTypes.REQUEST` sets`homepage.loading` on `true` and I can test it with the `console.log` on `Home.getInitialProps`.

I tried the same call it on the client, dispatching `fetchHomepage.request()` on `useEffect` and it's working!!!

I'm stuck! I need help 😓 I tried everything

**Comment by bbortt** [comment]
Maybe [this explanation](https://github.com/bmealhouse/next-redux-saga/issues/71#issuecomment-624515716) will help you.

I actually wonder that the `console.log` in this part
```js
Home.getInitialProps = async ({ store }) => {
	store.dispatch(fetchHomepage.request());
	console.log(store.getState().homepage.loading);
	return {};
};
```
does work on client side. Your API request must respond insanely fast :D

If you need to preload any data (e.g. security concerns or similar) you need to do that synchronously.

**Comment by dxit** [comment]
Thank you for the quick response :)
Actually, I see the `console.log` in the terminal, not on the browser console, so it would be on the server side.

The idea is to load the Meta information before the page is rendered (for SEO reasons). Would you recommend another way to archive it? Maybe my approach is wrong.
I mean, for the homepage I can preload the information. However, I need to load dynamically the information for the other pages. And that's why I would like to leverage `getInitialProps` with saga.

**Comment by bbortt** [comment]
ah ye, so the state's correctly reduced. however `redux-saga` does not execute the same way on the server side, as it does on the client side.

> Our code is located in one single file; the index.js:
```js
// Stop saga on the server
if (isServer) {
  store.dispatch(END)
  await store.sagaTask.toPromise()
}
```

if you *need* to load any data while ssr you must call your api synchronously. the problem with asynchronous tasks is that you cannot know how long they take. and if your request takes 30 seconds because of a server side data loading, where is the benefit of ssr? ;)

**Comment by dxit** [comment]
Alright, I think I need to review my plans for this project 😓.
Nevertheless, thank you very much for your support man 👍

**Comment by bbortt** [comment]
No problem. I'll close this for now. Feel free to reopen it if you got further questions.
