### ISSUE TITLE
Readme. Project Description

### ISSUE THREAD

**Issue by deresegetachew** [bmealhouse/next-redux-saga#74]
Hello;

As it is my project with nextjs and redux-saga works find and I was wondering the use of this library.
I think it will be good if there was a description on the readme, why this library exists, what problem it solves, and why one wants to use, and when to avoid it.

**Comment by bbortt** [comment]
I wonder - do you use server side rendering? Or do you export your app into static pages?
Because the goal of this project is for the first mentioned. There you need some utility to start, await and stop `redux-saga` on server side.
`redux-saga` alone works completly fine in the second case.
