### ISSUE TITLE
Next 9.3+ Compatibility

### ISSUE THREAD

**Issue by tkstang** [bmealhouse/next-redux-saga#75]
Are there currently any plans to update documentation and release a version compatible with Next 9.3's getServerSideProps?

**Comment by bbortt** [comment]
not yet. haven't been using Next.js recently. open for any PRs.

**Comment by bbortt** [comment]
In case you're wondering I just started working on it: https://github.com/bbortt/next-redux-saga/tree/feature/upgrade-to-next-9-4.
Need a little time to fix the tests.

**Comment by bbortt** [comment]
PR #78 was opened. happy for feedbacks.

**Comment by bbortt** [comment]
Released in [`next-redux-saga@beta`](https://www.npmjs.com/package/next-redux-saga/v/5.0.0-0).
