### ISSUE TITLE
outdated read.me & questions

### ISSUE THREAD

**Issue by BernardA** [bmealhouse/next-redux-saga#76]
I spent quite some time trying to implement this by following your read.me and got all types of errors.

Then I found out that some of the setup used in read.me is outdated, mostly from version 6 of `next-redux-wrapper`, namely:
- store no longer get initialState
- need to handle HYDRATE action in reducer 
- App no longer needs to wrap children with `Provider` 
- isServer is not passed on props
- store no longer passed to wrapped component prop

See: https://github.com/kirill-konshin/next-redux-wrapper

I then implemented it like below, which seems to work but I got a couple of questions:

- nextjs docs are very specific about not extending `App` (import App from 'next/app';), and they do not do that
in their official redux-saga example. Why is that necessary here or the inclusion of the HYDRATE action in each reducer would make that redundant?

- related to that is the `static async getInitialProps` also on `/pages/_app.js` and the same question on why and if that's still necessary.

Thanks

/ store/reduxWrapper.js

      import { createStore, applyMiddleware } from 'redux';
      import createSagaMiddleware from 'redux-saga';
      import { createWrapper } from 'next-redux-wrapper';
      import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
      import rootReducer from './reducers/index';
      import sagas from './sagas';

     const bindMiddleware = (middleware) => {
         const arrMiddleware = [middleware];
         if (process.env.NODE_ENV !== 'production') {
              return composeWithDevTools(applyMiddleware(...arrMiddleware));
         }
          return applyMiddleware(...arrMiddleware);
      };

      const configureStore = ({req = null}) => {
         const sagaMiddleware = createSagaMiddleware();
         const store = createStore(
              rootReducer,
              bindMiddleware(sagaMiddleware),
         );
          const isServer = typeof window === 'undefined';
         if (req || !isServer) {
            store.sagaTask = sagaMiddleware.run(sagas);
          }
         return store;
     }

export const wrapper = createWrapper(configureStore, { debug: true });

Then on /pages/_app.js

      import App from 'next/app';
     import withReduxSaga from 'next-redux-saga';
      import { wrapper } from '../store/reduxWrapper';

     class MyApp extends App { // ??????
    /* ??????? I commented out for now
    static async getInitialProps({ Component, ctx }) {
        let pageProps = {};

        if (Component.getInitialProps) {
            pageProps = await Component.getInitialProps(ctx);
        }

        return { pageProps };
    }
    */
    render() {
        const { Component, pageProps } = this.props;
        return (
            <Component {...pageProps} />
        );
      }
     }

     export default wrapper.withRedux(withReduxSaga(MyApp));

**Comment by fostyfost** [comment]
Hi, take a look at my example, maybe it will answer some of your questions.  https://github.com/fostyfost/next-with-redux-dynamic-modules

**Comment by bbortt** [comment]
I am heavily trying to update this repository, but examinations keeping me busy.. sorry. will come as soon as possible! (already forked and started a branch. basically only tests missing).
for your question regarding not extending `App`: `next.js` has put heavy focus on static pre-rendering and exporting of pages. extending `App` (data fetching via `getInitialProps`) makes this impossible and automatically enables ssr and/or a full (expensive) rendering on client side.
