### ISSUE TITLE
STOP MAINTAINING THIS REPOSITORY

### ISSUE THREAD

**Issue by bbortt** [bmealhouse/next-redux-saga#79]
hi @bmealhouse 

I think at this point it does not make sense to continue supporting this repository. `next.js` has grown massively and other packages with bedder support have covered this functionality (ssr with `redux-saga`) already.

from the `README.md` of [`next redux-wrapper`](https://github.com/kirill-konshin/next-redux-wrapper).
> Setting up Redux for static apps is rather simple: a single Redux store has to be created that is provided to all pages.
When Next.js static site generator or **server side rendering** is involved, however, things start to get complicated as another store instance is needed on the server to render Redux-connected components.
Furthermore, access to the Redux Store may also be needed during a page's getInitialProps.
**This is where next-redux-wrapper comes in handy**: It automatically creates the store instances for you and makes sure they all have the same state.
Moreover it allows to properly handle complex cases like App.getInitialProps (when using pages/_app) together with getStaticProps or getServerSideProps at individual page level.
Library provides uniform interface no matter in which Next.js lifecycle method you would like to use the Store.

if we take a look at the `next.js` "with-redux-saga" example, it doesn't even include `next-redux-saga` anymore. it is done via `next-redux-wrapper` and actually a duplicate of the example "with-redux-wrapper". `package.json`:
```json
"dependencies": {
  "next": "latest",
  "next-redux-wrapper": "^6.0.2",
  "react": "16.13.1",
  "react-dom": "16.13.1",
  "react-redux": "7.2.0",
  "redux": "4.0.5",
  "redux-saga": "1.1.3"
},
```

my suggestions is as following: I will create one last PR stating out the reason this package was abandoned, next you archive it -> "read only".

**Comment by bmealhouse** [comment]
@bbortt - I agree and I'm on board with this. Thanks again for all the time and effort you've contributed to maintaining this library.
